RealEstateApp/Models/RequestList/RequestViewModel.cs
using RealEstateApp.Domain.Entities;

namespace RealEstateApp.Models.RequestList
{
    public class RequestViewModel
    {
        public IEnumerable<Request> Requests { get; set; }
        public Request Request { get; set; }
    }
}

RealEstateApp/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models.RealEstateList;
using RealEstateApp.Models.RequestList;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace RealEstateApp.Controllers
{
    public class RequestController : Controller
    {
        private readonly RealEstateAppContext _context;

        public RequestController(RealEstateAppContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> RequestAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new RequestViewModel { Requests = await GetRequestsAsync() });
            }
            else
            {
                var realEstates = new RequestViewModel { Requests = await GetRequestsAsync() };
                var query = realEstates.Requests.Where(p => p.Name.Contains(searchString) || p.Phone.Contains(searchString)
                                                   || p.Email.Contains(searchString)).ToList();
                return View(new RequestViewModel { Requests = query });
            }
        }
        public async Task<IEnumerable<Request>> GetRequestsAsync()
        {
            return await _context.Requests.ToListAsync();
        }

        public async Task<Request> GetRequestAsync(int id)
        {
            return await _context.Requests.FirstOrDefaultAsync(x => x.Id == id);
        }
		public async Task<IActionResult> ChangeRequestStatusAsync(int id)
		{
            var item = _context.Requests.FirstOrDefaultAsync(x => x.Id == id).Result.Status = true;
            await _context.SaveChangesAsync();
			return RedirectToAction("Request");
		}
	}
}

RealEstateApp/Views/Shared/Components/Request/RequestViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Views.Shared.Components.Request
{
    public class RequestViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.Request request)
        {
            return View(request);
        }
    }
}

RealEstateApp/Views/Request/Request.cshtml
@using RealEstateApp.Models.RequestList;
@model RequestViewModel
@{
    Layout = "~/Views/EditRealEstate/_RealEstateLayout.cshtml";
}

<h1>Поиск</h1>
<div class="shadow rounded p-3 bg-white">
    <div class="d-flex flex-row justify-content-between">
        <form asp-controller="Request" asp-action="Request">
            <div class="d-flex flex-row justify-content-between">
                <div class="d-flex flex-row justify-content-between">
                    <div>
                        <div class="form-floating">
                            <input name="searchString"
                                   asp-for="Request.Email"
                                   type="text"
                                   class="form-control shadow-sm rounded"
                                   placeholder="Поиск">
                            <label asp-for="Request.Email">Поиск</label>
                        </div>
                        <span asp-validation-for="Request.Email" class="text-danger"></span>
                        <div class="text-danger">@ViewBag.Error</div>
                    </div>
                    <div class="col-1 d-flex">
                        <button class="btn btn-secondary shadows rounded" type="submit" data-bs-title="Добавить"
                                data-bs-toggle="tooltip">
                            Поиск
                        </button>
                    </div>
                </div>
            </div>
        </form>
        <form asp-controller="Request" asp-action="Request">
            <div class="d-flex flex-row">
                <button class="btn d-flex btn-secondary shadows rounded" id="buttonReset" type="submit" data-bs-title="Добавить"
                        data-bs-toggle="tooltip">
                    Сбросить
                </button>
            </div>
        </form>
    </div>
</div>

<hr />

<div class="estate align-items-center p-3 mt-3 rounded d-flex flex-row justify-content-start border-bottom">
    <div class="d-flex col">
        <label class="form-label">Идентификатор</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Отправитель</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Номер телефона</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Электронная почта</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Время отправки</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Статус заявки</label>
    </div>
    <div class="d-flex col">
        <label class="form-label">Действие</label>
    </div>
</div>
<div class="estates">
    @foreach (var request in Model.Requests)
    {
        @await Component.InvokeAsync("Request", request);
    }
</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/js/components/requestItem/Default.js"></script>
}

<style>
    .row {
        margin-top: 10px;
    }
</style>