RealEstateApp/Models/RealEstateList/RealEstateViewModel.cs
using RealEstateApp.Domain.Entities;
using System.ComponentModel.DataAnnotations;
namespace RealEstateApp.Models.RealEstateList
{
    public abstract class RealEstateViewModel
    {
        public IEnumerable<RealEstate>? RealEstates { get; set; }
        static RealEstateViewModel()
        {
            
        }

        /*
        public int TotalFloors { get; set; }
        public int TotalArea { get; set; }
        public int NumbersOfRooms { get; set; }
        public int Id {  get; set; }
        [Required(ErrorMessage = "Данное поле обязательно")]
        public string Address { get; set; }
        public decimal Price { get; set; }*/
    }

}

RealEstateApp/Controllers/DealController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Domain;
using RealEstateApp.Models.DealList;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Models.ClientList;

namespace RealEstateApp.Controllers
{
    public class DealController : Controller
    {
        private readonly RealEstateAppContext _context;
        public DealController(RealEstateAppContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> DealAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new DealViewModel { Deals = await GetDealsAsync() });
            }
            else
            {
                searchString = searchString.ToLower();
                var client = new DealViewModel { Deals = await GetDealsAsync() };
                var query = client.Deals.Where(p => p.IdRealEstate.ToString() == searchString || p.IdAgent.ToString() == searchString
                                                   || p.IdRealEstate.ToString() == searchString || p.Date.ToString() == searchString);
                return View(new DealViewModel { Deals = query });
            }
        }
        public async Task<IEnumerable<Deal>> GetDealsAsync()
        {
            return await _context.Deals.ToListAsync();
        }
    }
}

RealEstateApp/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models.RealEstateList;

namespace RealEstateApp.Controllers
{
    public class RealEstateController : BaseController
    {
        private readonly RealEstateAppContext _context;

        public RealEstateController(RealEstateAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() });
            }
            else
            {
                var realEstates = new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() };
                var query = realEstates.RealEstates.Where(p => p.Address.Contains(searchString)).ToList();
                return View(new RealEstateViewModel { RealEstates = query});
            }
        }

        public async Task<IEnumerable<RealEstate>> GetRealEstatesAsync()
        {
            return await _context.RealEstates.ToListAsync();
        }

        public async Task<RealEstate> GetRealEstateAsync(int id)
        {
            return await _context.RealEstates.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<IActionResult> CreateAsync(RealEstateViewModel realEstateViewModel)
        {
            if (!ModelState.IsValid)
            {
                realEstateViewModel.RealEstates = await GetRealEstatesAsync();
                return View("Index", realEstateViewModel);
            }

            await _context.RealEstates.AddAsync(new RealEstate
            {
                Address = realEstateViewModel.Address,
                Price = realEstateViewModel.Price,
                TotalArea = realEstateViewModel.TotalArea,
                NumberOfRooms = realEstateViewModel.NumbersOfRooms,
                TotalFloors = realEstateViewModel.TotalFloors
            });

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateAsync(RealEstateViewModel realEstateViewModel)
        {
            var estate = await _context.RealEstates.FirstOrDefaultAsync(i=>realEstateViewModel.Id == i.Id);
            if(estate != null)
            {
                if (realEstateViewModel.Address != null)
                {
                    estate.Address = realEstateViewModel.Address;
                    estate.Price = realEstateViewModel.Price;
                    _context.RealEstates.Update(estate);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var realEstate = await _context.RealEstates.FirstOrDefaultAsync(i => i.Id == id);
            if(realEstate != null)
            {
                _context.RealEstates.Remove(realEstate);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealEstateApp/Controllers/RealEstateLayoutController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Models.RealEstateList;

namespace RealEstateApp.Controllers
{
    public class RealEstateLayoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Clients()
        {
            return View("~/Views/EditRealEstate/Clients.cshtml");
        }

        public IActionResult Deals()
        {
            return View("~/Views/EditRealEstate/Deals.cshtml");
        }

    }
}

RealEstateApp/Views/Shared/Components/RealEstate/RealEstateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Domain.Entities;

namespace RealEstateApp.Views.Shared.Components.RealEstate
{
    public class RealEstateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.RealEstate realEstate)
        {
            return View(realEstate); 
        }
    }
}

RealEstateApp/Views/RealEstate/Index.cshtml
@using RealEstateApp.Models.RealEstateList;
@model RealEstateViewModel
@{
    Layout = "~/Views/RealEstate/_RealEstateLayout.cshtml";
    ViewData["Title"] = "RealEstateEmpty";
}


<div class="shadow rounded p-3 mt-5 bg-white">
    <form asp-action="Create">
        <div class="row">
            <div class="col-6">
                <div class="form-floating">
                    <input asp-for="Address"
                    type="text"
                    class="form-control shadow-sm rounded"
                    placeholder="Адрес объекта">
                    <label asp-for="Address">Адрес объекта</label>
                </div>
                <span asp-validation-for="Address" class="text-danger"></span>
                <div class="text-danger">@ViewBag.Error</div>
            </div>

            <div class="col-4">
                <div class="form-floating">
                    <input asp-for="Price"
                    type="number"
                    min="1"
                    step="any"
                    class="form-control shadow-sm rounded"
                    placeholder="Цена объекта">
                    <label asp-for="Price">Цена объекта</label>
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="col-1 d-flex">
                <button class="btn btn-success d-flex shadows rounded"
                        type="submit"
                        style="text-align:center; margin:auto;"                        
                        data-bs-title="Добавить"
                        data-bs-toggle="tooltip">Добавить                        
                </button>
            </div>
        </div>
        <div class="row">
            <div id="areaDiv" class="areaDiv col-2">
                <div class="form-floating">
                    <input asp-for="TotalArea" 
                           type="number" id="totalAreaInput"
                           min="1"
                           step="any"
                           class="form-control shadow-sm rounded"
                           placeholder="Адрес объекта">
                    <label asp-for="TotalArea">Площадь</label>
                </div>
                <span asp-validation-for="TotalArea" class="text-danger"></span>
                <div class="text-danger">@ViewBag.Error</div>
            </div>
             
            <div id="floorsDiv" class="col-3">
                <div class="form-floating">
                    <input asp-for="TotalFloors" 
                           type="number" id="totalFloorsInput"
                           min="1"
                           step="any"
                           class="form-control shadow-sm rounded"
                           placeholder="Цена объекта">
                    <label asp-for="TotalFloors">Количество этажей</label>
                </div>
                <span asp-validation-for="TotalFloors" class="text-danger"></span>
            </div>
             
            <div id="roomsDiv" class="roomsDiv col-3">
                <div class="form-floating">
                    <input asp-for="NumbersOfRooms" 
                           type="number" id="totalRoomsInput"
                           min="1"
                           step="any"
                           class="form-control shadow-sm rounded"
                           placeholder="Цена объекта">
                    <label asp-for="NumbersOfRooms">Количество комнат</label>
                </div>
                <span asp-validation-for="NumbersOfRooms" class="text-danger"></span>
            </div>
        </div>
    </form>
</div>
<hr/>
<h1>Поиск</h1>
<div class="shadow rounded p-3 bg-white">
    <div class="d-flex flex-row justify-content-between">
        <form asp-controller="RealEstate"  asp-action="Index">
            <div class="d-flex flex-row justify-content-between">
                <div class="d-flex flex-row justify-content-between">
                    <div>
                        <div class="form-floating">
                            <input name="searchString"
                                   asp-for="Address"
                                   type="text"
                                   class="form-control shadow-sm rounded"
                                   placeholder="Адрес объекта">
                            <label asp-for="Address">Адрес объекта</label>
                        </div>
                        <span asp-validation-for="Address" class="text-danger"></span>
                        <div class="text-danger">@ViewBag.Error</div>
                    </div>
                    <div class="col-1 d-flex">
                        <button class="btn btn-secondary shadows rounded" type="submit" data-bs-title="Добавить"
                                data-bs-toggle="tooltip">Поиск
                        </button>
                    </div>
                </div>                
            </div>
        </form>
        <form asp-controller="RealEstate" asp-action="Index">
            <div class="d-flex flex-row">
                <button class="btn d-flex btn-secondary shadows rounded" id="buttonReset" type="submit" data-bs-title="Добавить"
                        data-bs-toggle="tooltip">
                    Сбросить
                </button>
            </div>
        </form>
        </div>
</div>

<hr/>

<div class="estate align-items-center p-3 mt-3 rounded d-flex flex-row justify-content-between border-bottom">
    <div class="d-flex align-items-center">
        <label class="form-label">Идентификатор</label>
    </div>
    <div >
        <label class="form-label">Адрес объекта</label>
    </div>
    <div >
        <label class="form-label">Цена объекта</label>
    </div>
    <div>
        <label class="form-label">Площадь</label>
    </div>
    <div>
        <label class="form-label">Кол-во комнат</label>
    </div>
    <div>
        <label class="form-label">Этаж</label>
    </div>
    <div>
        <label class="form-label">Действие</label>
    </div>
 </div>
<div class="estates">
    @foreach (var estate in Model.RealEstates)
    {
        
        @await Component.InvokeAsync("RealEstate", estate);
        
    }
</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/js/components/realEstateItem/Default.js"></script>
}

<style>
    .row {
       margin-top:10px;
    }
</style>

RealEstateApp/Views/RealEstate/_RealEstateLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@* @ViewData["Title"] - RealEstateApp *@Админ-панель</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealEstateApp.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="d-flex justify-content-center">
        <header class="px-5 pt-1">
            <nav class="homebar navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-0 box-shadow mb-3">
                <div class="d-flex container-fluid border-0">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-2">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RealEstate" asp-action="Index">RealEstates</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Client">Clients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Deal" asp-action="Deal">Deals</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Index">Выход</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>
    <div class="container">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RealEstateApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>