RealEstateApp/Models/RealEstateList/CatalogViewModel.cs
using RealEstateApp.Domain.Entities;
using System.ComponentModel.DataAnnotations;

namespace RealEstateApp.Models.RealEstateList
{
    public class CatalogViewModel : RealEstateViewModel
    {
        public RealEstate? RealEstate { get; set; }

        [Required(ErrorMessage = "Данное поле обязательно")]
        public Request Request { get; set; }
    }
}

RealEstateApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models;
using RealEstateApp.Models.RealEstateList;
using System.Diagnostics;

namespace RealEstateApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly RealEstateAppContext _context;


        public HomeController(ILogger<HomeController> logger, RealEstateAppContext context)
        {
            _logger = logger;
            _context = context;

        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CatalogAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new CatalogViewModel { RealEstates = await GetRealEstatesAsync() });
            }
            else
            {
                var realEstates = new CatalogViewModel { RealEstates = await GetRealEstatesAsync() };
                var query = realEstates.RealEstates.Where(p => p.Address.Contains(searchString)).ToList();
                return View(new CatalogViewModel { RealEstates = query });
            }
        }
        public async Task<IActionResult> CatalogItemAsync(int id)
        {
            return View(new CatalogViewModel { RealEstate = await GetRealEstateAsync(id)});
        }
        public async Task<RealEstate> GetRealEstateAsync(int id)
        {
            return await _context.RealEstates.FirstOrDefaultAsync(x => x.Id == id);
        }
        public async Task<IEnumerable<RealEstate>> GetRealEstatesAsync()
        {
            return await _context.RealEstates.ToListAsync();
        }

        public async Task<IActionResult> CreateRequestAsync(CatalogViewModel catalogViewModel)
        {
            /*if (!ModelState.IsValid) return Redirect($"~/home/catalogitem?id={catalogViewModel.RealEstate.Id}");*/

            if (!catalogViewModel.Request.IsValid()) return Redirect($"~/home/catalogitem?id={catalogViewModel.RealEstate.Id}");

            await _context.Requests.AddAsync(new Request
            {
                Name = catalogViewModel.Request.Name,
                Phone = catalogViewModel.Request.Phone,
                Email = catalogViewModel.Request.Email,
                IdRealEstate = catalogViewModel.RealEstate.Id,
                RequestDate = DateTime.Now,
                Status = false
            });
            await _context.SaveChangesAsync();
            return Redirect($"~/home/catalogitem?id={catalogViewModel.RealEstate.Id}");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RealEstateApp/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models.RealEstateList;

namespace RealEstateApp.Controllers
{
    public class RealEstateController : BaseController
    {
        private readonly RealEstateAppContext _context;

        public RealEstateController(RealEstateAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() });
            }
            else
            {
                var realEstates = new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() };
                var query = realEstates.RealEstates.Where(p => p.Address.Contains(searchString)).ToList();
                return View(new RealEstateViewModel { RealEstates = query});
            }
        }

        public async Task<IEnumerable<RealEstate>> GetRealEstatesAsync()
        {
            return await _context.RealEstates.ToListAsync();
        }

        public async Task<RealEstate> GetRealEstateAsync(int id)
        {
            return await _context.RealEstates.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<IActionResult> CreateAsync(RealEstateViewModel realEstateViewModel)
        {
            if (!ModelState.IsValid)
            {
                realEstateViewModel.RealEstates = await GetRealEstatesAsync();
                return View("Index", realEstateViewModel);
            }

            await _context.RealEstates.AddAsync(new RealEstate
            {
                Address = realEstateViewModel.Address,
                Price = realEstateViewModel.Price,
                TotalArea = realEstateViewModel.TotalArea,
                NumberOfRooms = realEstateViewModel.NumbersOfRooms,
                TotalFloors = realEstateViewModel.TotalFloors
            });

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateAsync(RealEstateViewModel realEstateViewModel)
        {
            var estate = await _context.RealEstates.FirstOrDefaultAsync(i=>realEstateViewModel.Id == i.Id);
            if(estate != null)
            {
                if (realEstateViewModel.Address != null)
                {
                    estate.Address = realEstateViewModel.Address;
                    estate.Price = realEstateViewModel.Price;
                    _context.RealEstates.Update(estate);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var realEstate = await _context.RealEstates.FirstOrDefaultAsync(i => i.Id == id);
            if(realEstate != null)
            {
                _context.RealEstates.Remove(realEstate);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealEstateApp/Views/Shared/Components/RealEstateListItem/RealEstateListItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Views.Shared.Components.RealEstateListItem
{
    public class RealEstateListItemViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.RealEstate realEstate)
        {
            return View(realEstate);
        }
    }
}

RealEstateApp/Views/Home/Catalog.cshtml
@using RealEstateApp.Models.RealEstateList;
@model CatalogViewModel
@{

}

<div>

</div>
<h1>Каталог</h1>
<p></p>
<div class="searchMenu">
   @*  <div class="imgContainer">
        <img class="bgimage" src="~/resources/city-firstimage.jpg"/>
    </div> *@
    <div class="shadow rounded p-3 bg-white">
        <h1>Поиск</h1>
        <div class="searchBar">
            <form asp-controller="Home" asp-action="Catalog">
                <div class="row">
                    <div class="col-5">
                        <div class="form-floating">
                            <input name="searchString"
                                   asp-for="@Model.RealEstate.Address"
                                   type="text"
                                   class="form-control shadow-sm rounded"
                                   placeholder="Адрес объекта">
                            <label>Адрес объекта</label>
                        </div>
                        <div class="text-danger">@ViewBag.Error</div>
                    </div>
                    <div class="col-1 d-flex">
                        <button class="btn btn-secondary shadows rounded" type="submit" data-bs-title="Добавить"
                                data-bs-toggle="tooltip">
                            Поиск
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <hr />
</div>
<div class="estates">
    @foreach (var estate in Model.RealEstates)
    {
        @await Component.InvokeAsync("RealEstateListItem", estate);
    }
</div>


<style>
    .searchMenu{
        justify-content:center;
        align-items:center;
        /* background-image: url("~/resources/city-firstimage.jpg"); */
    }
    .searchBar{
        
    }

    .imgContainer {
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;
                background-size:cover;
    }
    h1{
        justify-content:center;
        text-align:center;
        margin:10px;
    }
    .bgimage{
        flex-shrink: 0;
        min-width: 100%;
        min-height: 100%;     
        object-fit:contain
    }
</style>

RealEstateApp/Views/Home/CatalogItem.cshtml
@using RealEstateApp.Models.RealEstateList;
@model CatalogViewModel
@{

}


<div class="singlePage d-flex">
    <div class="col">
        <div>      
            <div class="d-flex">   
                <div>
                    <form asp-controller="Home" asp-action="CreateRequest">
                        @Html.HiddenFor(_ => _.RealEstate.Address)
                        <div class="aboba">
                            <p>@Model.RealEstate.Address</p>
                        </div>
                        <div class="d-flex flex-row">
                            <div class="col">
                                <p></p>
                                <div class="crop">
                                    <img src="@Model.RealEstate.Photo" />
                                </div>
                            </div>
                            <div class="col-1"></div>
                            <div class="d-flex col-3 align-items-start p-3 mt-3 rounded justify-content-start border border-success">
                                    @Html.HiddenFor(_ => _.RealEstate.Id)
                                    <div>
                                        <div class="mb-3 d-flex input-group-text">
                                            <div action="form-floating">
                                                <label class="form-label d-flex">Имя</label>
                                                <input type="text" asp-for="@Model.Request.Name" class="form-control" placeholder="Введите логин" />
                                                <span asp-validation-for="Request.Name" class="text-danger"></span>
                                                <div class="text-danger">@ViewBag.Error</div>
                                            </div>
                                        </div>

                                        <div class="mb-3 d-flex input-group-text">
                                            <div action="form-floating">
                                                <label asp-for="Request.Phone" class="form-label d-flex">Телефон</label>
                                                <input id="inputTelephone" type="text" asp-for="@Model.Request.Phone" class="form-control shadow-sm rounded" placeholder="Номер телефона"/>
                                            </div>
                                            <span asp-validation-for="Request.Phone" class="text-danger"></span>
                                            <div class="text-danger">@ViewBag.Error</div>
                                        </div>
                                       

                                        <div class="mb-3 d-flex input-group-text">
                                            <div action="form-floating">
                                                <label class="form-label d-flex">Электронная почта</label>
                                                <input type="text" class="form-control" asp-for="@Model.Request.Email" placeholder="Введите логин" />
                                                <span asp-validation-for="Request.Email" class="text-danger"></span>
                                                <div class="text-danger">@ViewBag.Error</div>
                                            </div>
                                        </div>
                                        <button class="btn btn-success" type="sumbit">
                                            Отправить заявку
                                        </button>
                                    </div>                          
                            </div>
                        </div>
                        <p></p>
                        <h3>Описание</h3>
                        <div>
                            <div class="d-flex col">
                                <span>Адрес: @Model.RealEstate.Address</span>
                            </div>
                            <div class="d-flex col">
                                <span>Цена: @Model.RealEstate.Price рублей</span>
                            </div>
                            <div class="d-flex col">
                                <span>Площадь: @Model.RealEstate.TotalArea кв. м2</span>
                            </div>
                            <div class="d-flex col">
                                <span>Количество комнат: @Model.RealEstate.NumberOfRooms</span>
                            </div>
                            <div class="d-flex col">
                                <span>Этаж: @Model.RealEstate.TotalFloors</span>
                            </div>
                        </div>
                        <p></p>
                        <h3>Расположение на карте</h3>
                        <p></p>
                        <div>
                            <div id="mapDiv" style="width: 800px; height: 500px"></div>
                            <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
                            <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
                            <script>
                                // position we will use later
                                var lat = parseFloat(@Model.RealEstate.Latitude).toFixed(6);
                                var lon = parseFloat(@Model.RealEstate.Longitude).toFixed(6);
                                // initialize map
                                map = L.map('mapDiv').setView([lat, lon], 20);
                                // set map tiles source
                                L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                                    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
                                    maxZoom: 18,
                                }).addTo(map);
                                // add marker to the map
                                marker = L.marker([lat, lon]).addTo(map);
                                // add popup to the marker
                                marker.bindPopup("Ваш объект").openPopup();
                            </script>
                        </div>
                        <div style="height:50px"> </div>
                    </form>
                </div>                
            </div>
        </div>
    </div>
    
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
}

<style>
    .fillDiv {
        display: block;
        height: 100%;
        width: 100%;
        text-decoration: none;
    }

    .aboba {
        word-wrap: break-word;
    }

    div.aboba{
        word-wrap: break-word;
        font-size: 24px;
        width: 1140px;
        max-height: 500px;
        overflow: hidden;
    }

    .aboba p {
        word-wrap:break-word;
    }

    .singlePage {
        justify-content:end;
        max-width: 80%;
        margin: 0 auto;
        padding: 0 20px;
        max-height: 300px;
    }

    .slick {
        display: flex;
        justify-content: end;
    }

    .flex {
        display: flex;
        justify-content: space-between;
    }

    .crop {
        width: 1140px;
        max-height: 500px;
        overflow: hidden;
    }

        .crop img {
            max-width: 100%;
            height: 100%;
        }

    #properties-details {
        word-wrap: normal;
    }

    #properties .container {
        position: relative;
    }

    .properties-slider img {
        width: auto;
        height: auto;
        display: block;
        text-decoration: none;
    }
</style>

RealEstateApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<body>
    <div class="homepage d-flex justify-content-between">
        <div class="textContainer d-flex">
            <div class="wrapper d-flex flex-column justify-content-lg-start col pt-5">
                <h1 class="title display-5">Найдите свое место мечты!</h1>
                <p>
                    Ваш путь к идеальному жилищу начинается здесь! Наше риэлторское агентство предлагает вам не только квалифицированную помощь
                    в поиске недвижимости, но и настоящее понимание ваших потребностей и мечтаний.
                    Мы работаем для вашего комфорта и уверенности в выборе. Доверьте нам заботу о вашем будущем доме,
                    и мы сделаем все возможное, чтобы сделать вашу мечту о жилье реальностью!
                </p>
                <button type="button" class="button btn-success rounded shadow border-1" asp-area="" value="Начать!"
                onclick="location.href='@Url.Action("catalog", "home")'" asp-controller="RealEstate" asp-action="Index">Начать!</button>
                <div class="boxes d-flex flex-row">
                    <div class=""><h2>2+</h2><h3>Года опыта</h3></div>
                    <div class="ml-3"><h2>Множество</h2><h3>наград!</h3></div>
                    <div class="ml-3"><h2>130+</h2><h3>Позиций</h3></div>
                </div>
            </div>
        </div>
        <div class="imgContainer d-flex position-relative">
            <img class="" src="~/resources/bg.png" alt="" />
        </div>
    </div>
</body>

<style type="text/css">
    .boxes{
        display: flex;
        justify-content: space-between;
    }

    .textContainer {
        flex: 3;
    }

    .wrapper {
        padding-right: 100px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        gap: 50px;
        height: 100%;
    }

    .homePage {
        display: flex;
        height: 100%;
    }

    .imgContainer{
        flex: 2;
        background-color: #fcf5f3;
        position: relative;
        display: flex;
        align-items: center;
    }

    img {
        width: 115%;
        position: absolute;
        right: 0;
    }


</style>