RealEstateApp/Models/RealEstateList/RealEstateViewModel.cs
using RealEstateApp.Domain.Entities;
using System.ComponentModel.DataAnnotations;
namespace RealEstateApp.Models.RealEstateList
{
    public abstract class RealEstateViewModel
    {
        public IEnumerable<RealEstate>? RealEstates { get; set; }
        static RealEstateViewModel()
        {
            
        }

        /*
        public int TotalFloors { get; set; }
        public int TotalArea { get; set; }
        public int NumbersOfRooms { get; set; }
        public int Id {  get; set; }
        [Required(ErrorMessage = "Данное поле обязательно")]
        public string Address { get; set; }
        public decimal Price { get; set; }*/
    }

}

RealEstateApp/Controllers/EditRealEstateController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models.RealEstateList;

namespace RealEstateApp.Controllers
{
    public class EditRealEstateController : BaseController
    {
        private readonly RealEstateAppContext _context;

        public EditRealEstateController(RealEstateAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new EditViewModel { RealEstates = await GetRealEstatesAsync() });
            }
            else
            {
                var realEstates = new EditViewModel { RealEstates = await GetRealEstatesAsync() };
                var query = realEstates.RealEstates.Where(p => p.Address.Contains(searchString)).ToList();
                return View(new EditViewModel { RealEstates = query});
            }
        }

        public async Task<IEnumerable<RealEstate>> GetRealEstatesAsync()
        {
            return await _context.RealEstates.ToListAsync();
        }

        public async Task<RealEstate> GetRealEstateAsync(int id)
        {
            return await _context.RealEstates.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<IActionResult> CreateAsync(EditViewModel editViewModel)
        {
            if (!ModelState.IsValid)
            {
                editViewModel.RealEstates = await GetRealEstatesAsync();
                return View("Index", editViewModel);
            }

            await _context.RealEstates.AddAsync(new RealEstate
            {
                Address = editViewModel.RealEstate.Address,
                Price = editViewModel.RealEstate.Price,
                TotalArea = editViewModel.RealEstate.TotalArea,
                NumberOfRooms = editViewModel.RealEstate.NumberOfRooms,
                TotalFloors = editViewModel.RealEstate.TotalFloors,
                Latitude = editViewModel.RealEstate.Latitude,
                Longitude = editViewModel.RealEstate.Longitude,
                Photo = editViewModel.RealEstate.Photo
            });

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateAsync(EditViewModel editViewModel)
        {
            var estate = await _context.RealEstates.FirstOrDefaultAsync(i=> editViewModel.Id == i.Id);
            if(estate != null)
            {
                if (editViewModel.Address != null)
                {
                    estate.Address = editViewModel.Address;
                    estate.Price = editViewModel.Price;
                    estate.NumberOfRooms = editViewModel.NumberOfRooms;
                    estate.TotalArea = editViewModel.TotalArea;
                    estate.TotalFloors = editViewModel.TotalFloors;
                    _context.RealEstates.Update(estate);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var realEstate = await _context.RealEstates.FirstOrDefaultAsync(i => i.Id == id);
            if(realEstate != null)
            {
                _context.RealEstates.Remove(realEstate);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealEstateApp/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstateApp.Domain;
using RealEstateApp.Domain.Entities;
using RealEstateApp.Models.RealEstateList;

namespace RealEstateApp.Controllers
{
    public class RealEstateController : BaseController
    {
        private readonly RealEstateAppContext _context;

        public RealEstateController(RealEstateAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync(string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() });
            }
            else
            {
                var realEstates = new RealEstateViewModel { RealEstates = await GetRealEstatesAsync() };
                var query = realEstates.RealEstates.Where(p => p.Address.Contains(searchString)).ToList();
                return View(new RealEstateViewModel { RealEstates = query});
            }
        }

        public async Task<IEnumerable<RealEstate>> GetRealEstatesAsync()
        {
            return await _context.RealEstates.ToListAsync();
        }

        public async Task<RealEstate> GetRealEstateAsync(int id)
        {
            return await _context.RealEstates.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<IActionResult> CreateAsync(RealEstateViewModel realEstateViewModel)
        {
            if (!ModelState.IsValid)
            {
                realEstateViewModel.RealEstates = await GetRealEstatesAsync();
                return View("Index", realEstateViewModel);
            }

            await _context.RealEstates.AddAsync(new RealEstate
            {
                Address = realEstateViewModel.Address,
                Price = realEstateViewModel.Price,
                TotalArea = realEstateViewModel.TotalArea,
                NumberOfRooms = realEstateViewModel.NumbersOfRooms,
                TotalFloors = realEstateViewModel.TotalFloors
            });

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateAsync(RealEstateViewModel realEstateViewModel)
        {
            var estate = await _context.RealEstates.FirstOrDefaultAsync(i=>realEstateViewModel.Id == i.Id);
            if(estate != null)
            {
                if (realEstateViewModel.Address != null)
                {
                    estate.Address = realEstateViewModel.Address;
                    estate.Price = realEstateViewModel.Price;
                    _context.RealEstates.Update(estate);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var realEstate = await _context.RealEstates.FirstOrDefaultAsync(i => i.Id == id);
            if(realEstate != null)
            {
                _context.RealEstates.Remove(realEstate);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealEstateApp/Views/Shared/Components/Client/ClientViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Domain.Entities;

namespace RealEstateApp.Views.Shared.Components.RealEstate
{
    public class ClientViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.Client client)
        {
            return View(client);
        }
    }
}

RealEstateApp/Views/Shared/Components/Deal/DealViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Views.Shared.Components.Deal
{
    public class DealViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.Deal deal)
        {
            return View(deal);
        }
    }
}

RealEstateApp/Views/Shared/Components/RealEstate/RealEstateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Domain.Entities;

namespace RealEstateApp.Views.Shared.Components.RealEstate
{
    public class RealEstateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.RealEstate realEstate)
        {
            return View(realEstate); 
        }
    }
}

RealEstateApp/Views/Shared/Components/RealEstateListItem/RealEstateListItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Views.Shared.Components.RealEstateListItem
{
    public class RealEstateListItemViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.RealEstate realEstate)
        {
            return View(realEstate);
        }
    }
}

RealEstateApp/Views/Shared/Components/Request/RequestViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Views.Shared.Components.Request
{
    public class RequestViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(RealEstateApp.Domain.Entities.Request request)
        {
            return View(request);
        }
    }
}

RealEstateApp/Views/Shared/Components/RealEstate/Default.cshtml
@using RealEstateApp.Domain.Entities;
@model RealEstate
@{

}

<div class="estate align-items-center p-3 mt-3 rounded d-flex flex-row justify-content-start border border-success" data-id="@Model.Id">
	<div class="d-flex col">
		<label class="form-label" asp-for="Id">@Model.Id</label>
	</div>
	<div class="d-flex col">
		<label class="form-label text-break" asp-for="Address">@Model.Address</label>
	</div>
	<div class="d-flex col">
		<label class="form-label" asp-for="Price">@Model.Price</label>
	</div>
	<div class="d-flex col">
		<label class="form-label" asp-for="TotalArea">@Model.TotalArea</label>
	</div>
	<div class="d-flex col">
		<label class="form-label" asp-for="TotalFloors">@Model.TotalFloors</label>
	</div>
	<div class="d-flex col">
		<label class="form-label" asp-for="NumberOfRooms">@Model.NumberOfRooms</label>
		<input asp-for="Latitude" type="hidden" />
		<input asp-for="Longitude" type="hidden" />
		<input asp-for="Photo" type="hidden" />
	</div>
	<div class="crop d-flex col ">
		<img src="@Model.Photo"/>
	</div>
	<div class="null-column d-flex col">
	</div>
	<div class="col">
		<button type="button" class="btn btn-success edit mb-1" data-bs-toggle="modal" data-bs-target="#exampleModalEdit" id="@Model.Id" data-bs-placement="top" title="Редактировать">Редактировать
			</button>
		<button type="button" class="btn btn-primary edit mb-1" data-bs-toggle="modal" data-bs-target="#exampleModalMap" id="@Model.Id" data-bs-placement="top" title="Редактировать">
			Расположение
		</button>
		<form asp-controller="EditRealEstate" asp-action="Delete">
			@Html.HiddenFor(m=>m.Id)
			<button type="submit" class="btn btn-danger" data-bs-toggle="tooltip" data-bs-placement="top" title="Удалить">Удалить
			</button>
		</form>
	</div>
</div>

<!-- Модальное окно редактирования -->
<div class="modal fade" id="exampleModalEdit" aria-labelledby="exampleModalLabel" aria-hidden="true" data-id="@Model.Id">
	<form asp-controller="EditRealEstate" asp-action="Update">
		<div class="modal-dialog d-flex justify-content-center">
			<div class="modal-content m-5 d-flex">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Редактирование данных недвижимости</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
				</div>
				<div class="modal-body">
					<div class="form-floating disabled mb-3">
						<input type="text" asp-for="@Model.Id"
							   class="form-control shadow-sm rounded"
							   placeholder="Идентификатор объекта"
							   id="IdEstate" readonly>
						<label asp-for="@Model.Id">Идентификатор объекта</label>
					</div>
					<div class="form-floating mb-3">
						<input type="text" asp-for="@Model.Address"
							   class="form-control shadow-sm rounded"
							   placeholder="Адрес объекта"
							   id="AddressInput">
						<label asp-for="@Model.Address">Адрес объекта</label>
					</div>
					<span asp-validation-for="@Model.Address" class="text-danger"></span>
					<div class="text-danger">@ViewBag.Error</div>
					<div class="form-floating mb-3">
						<input asp-for="@Model.Price"
							   type="number"
							   min="1"
							   step="any"
							   class="form-control shadow-sm rounded"
							   placeholder="Цена объекта"
							   id="PriceInput">
						<label asp-for="@Model.Price">Цена объекта</label>
					</div>
					<span asp-validation-for="@Model.Price" class="text-danger"></span>
					<div class="form-floating mb-3">
						<input type="number" asp-for="@Model.TotalArea"
							   class="form-control shadow-sm rounded"
							   min="1"
							   step="any"
							   placeholder="Площадь объекта"
							   id="AreaInput">
						<label asp-for="@Model.TotalArea">Площадь объекта</label>
					</div>
					<span asp-validation-for="@Model.TotalArea" class="text-danger"></span>
					<div class="form-floating mb-3">
						<input type="number" asp-for="@Model.TotalFloors"
							   class="form-control shadow-sm rounded"
							   min="1"
							   step="any"
							   placeholder="Кол-во этажей"
							   id="FloorsInput">
						<label asp-for="@Model.TotalFloors">Кол-во этажей</label>
					</div>
					<span asp-validation-for="@Model.TotalFloors" class="text-danger"></span>
					<div class="form-floating mb-3">
						<input type="number" asp-for="@Model.NumberOfRooms"
							   class="form-control shadow-sm rounded"
							   min="1"
							   step="any"
							   placeholder="Кол-во комнат"
							   id="RoomsInput">
						<label asp-for="@Model.NumberOfRooms">Кол-во комнат</label>
					</div>
					<span asp-validation-for="@Model.NumberOfRooms" class="text-danger"></span>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary p-2" data-bs-dismiss="modal">Закрыть</button>
					<button type="sumbit" class="btn btn-success">Сохранить изменения</button>
				</div>
			</div>
		</div>
		</form>
</div>

<!-- Модальное окно расположения -->
<div class="modal fade" id="exampleModalMap" aria-labelledby="exampleModalLabel" aria-hidden="true" data-id="@Model.Id">
	<form asp-controller="RealEstate" asp-action="Update">
		<div class="modal-dialog d-flex justify-content-center">
			<div class="modal-content m-5 d-flex">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Расположение недвижимости</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
				</div>
				<div class="modal-body">
					<div class="container-fluid">
						<div id="mapDiv" style="width: 400px; height: 500px"></div>
						<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
						<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary p-2" data-bs-dismiss="modal">Закрыть</button>
				</div>
			</div>
		</div>
	</form>
</div>

@section Scripts {
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
}

<style>

	.crop {
		width: 500px;
		max-height: 500px;
		overflow: hidden;
	}

		.crop img {
			max-width: 200px;
			height: 100px;
		}

	.null-column {
		max-width: 50px;
	}

</style>